trigger:
- main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)'
    gradleWrapperFile: '$(Build.Repository.LocalPath)/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build test assembleRelease assembleDebug assembleAndroidTest bundleRelease'
    sonarQubeRunAnalysis: false
    
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'keystore1'
    apksignerKeystorePassword: '12345678'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: '12345678'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy AAB files'
  inputs:
    contents: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Bash@1
  displayName: 'List AAB output directory'
  inputs:
    targetType: 'inline'
    script: |
      echo "Listing files in the AAB output directory:"
      ls $(Build.SourcesDirectory)/app/build/outputs/bundle/release/
