trigger:
- main

pr:
  - main

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)'
    gradleWrapperFile: '$(Build.Repository.LocalPath)/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build test assembleRelease assembleDebug assembleAndroidTest bundleRelease'
    sonarQubeRunAnalysis: false
    
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'keystore1'
    apksignerKeystorePassword: '12345678'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: '12345678'
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    
- task: CopyFiles@2
  displayName: 'Copy deliverables'
  inputs:
    Contents: '*.aab'
    TargetFolder: 'drop'

- task: PublishBuildArtifacts@1
